project:
  type: website

website:
  title: "EmreKara-Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/emrekaragh
      - icon: linkedin
        href: https://www.linkedin.com/in/emrekara-ai/
format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css
execute:
  freeze: auto


