project:
  type: website

website:
  favicon: icon.png
  title: "EmreKara-Blog"
  navbar:
    right:
      - index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/emrekaragh
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/emrekara-ai/
        target: _blank
  google-analytics: 
    tracking-id: "G-43792F961J"
format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css
execute:
  freeze: auto


